language: python

python:
  - 2.7
  - 3.5

env:
  global:
    - PSYCOPG2_TESTDB=psycopg2_test
    - PSYCOPG2_TESTDB_HOST=localhost

before_script:
  - psql -c 'create database psycopg2_test;' -U postgres

install:
  - python setup.py install

script: make check
